### ISSUE TITLE
Request for unofficial clarification

### ISSUE THREAD

**Issue by tagawa** [adriangoransson/duckduckgo-bangs#1]
Hi. Thanks for making this add-on to help people use DuckDuckGo more easily.

Unfortunately we (DuckDuckGo) sometimes hear about users being confused about what's an official add-on and what isn't. To avoid this confusion, please could you:

    Change the logo so it doesn't feature the "Dax the duck" mascot,
    Make it clear your usage is "unofficial" in the description?

Thanks in advance.

**Comment by adriangoransson** [comment]
Sorry about that! I've updated the description and image in the [addons listing](https://addons.mozilla.org/en-GB/firefox/addon/search-duckduckgo-bangs/) and the repository readme.

**Comment by tagawa** [comment]
Hi again. That was quick! Thank you very much for making the change.
